<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/bootstrap.php';
$pdo=db();
$sql=[];
$sql[]="CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL, username VARCHAR(80) NOT NULL UNIQUE, email VARCHAR(160) NULL,
 password_hash VARCHAR(255) NOT NULL, role VARCHAR(40) NOT NULL,
 permission_overrides JSON NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, session_version INT NOT NULL DEFAULT 1,
 force_password_change TINYINT(1) NOT NULL DEFAULT 1, last_login_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_users_role(role), INDEX idx_users_active(is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS login_attempts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL, ip_address VARCHAR(64) NOT NULL,
 succeeded TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_login_lookup(username,ip_address,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS settings (
 setting_key VARCHAR(120) PRIMARY KEY, value_json LONGTEXT NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS financial_monthly (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, year INT NOT NULL, month TINYINT NOT NULL,
 revenue DECIMAL(22,2) NOT NULL DEFAULT 0,cogs DECIMAL(22,2) NOT NULL DEFAULT 0,opex DECIMAL(22,2) NOT NULL DEFAULT 0,
 expense DECIMAL(22,2) NOT NULL DEFAULT 0,gross_profit DECIMAL(22,2) NOT NULL DEFAULT 0,net_profit DECIMAL(22,2) NOT NULL DEFAULT 0,
 ebitda DECIMAL(22,2) NOT NULL DEFAULT 0,depreciation DECIMAL(22,2) NOT NULL DEFAULT 0,cash_in DECIMAL(22,2) NOT NULL DEFAULT 0,
 cash_out DECIMAL(22,2) NOT NULL DEFAULT 0,cash_net DECIMAL(22,2) NOT NULL DEFAULT 0,cash_balance DECIMAL(22,2) NOT NULL DEFAULT 0,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_fin_month(year,month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS service_monthly (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,name VARCHAR(190) NOT NULL,value DECIMAL(22,2) NOT NULL DEFAULT 0,tx_count INT NOT NULL DEFAULT 0,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_service(year,month,name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS customer_monthly (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,name VARCHAR(190) NOT NULL,alias VARCHAR(80) NOT NULL,value DECIMAL(22,2) NOT NULL DEFAULT 0,tx_count INT NOT NULL DEFAULT 0,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_customer(year,month,name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS invoices (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,invoice_no VARCHAR(100) NOT NULL,original_invoice VARCHAR(100) NULL,tax_invoice VARCHAR(100) NULL,
 invoice_date DATE NULL,customer VARCHAR(190) NOT NULL,alias VARCHAR(80) NULL,service TEXT NULL,category VARCHAR(150) NULL,dpp DECIMAL(22,2) NOT NULL DEFAULT 0,ppn DECIMAL(22,2) NOT NULL DEFAULT 0,status VARCHAR(40) NOT NULL DEFAULT 'APPROVED',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_invoice(invoice_no),INDEX idx_invoice_year_month(year,month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS receivable_snapshots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,customer VARCHAR(190) NOT NULL,alias VARCHAR(80) NULL,debit DECIMAL(22,2) NOT NULL DEFAULT 0,credit DECIMAL(22,2) NOT NULL DEFAULT 0,ending DECIMAL(22,2) NOT NULL DEFAULT 0,status VARCHAR(40) NOT NULL,due_date DATE NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_ar(year,month,customer)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS payable_snapshots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,vendor VARCHAR(190) NOT NULL,beginning DECIMAL(22,2) NOT NULL DEFAULT 0,payment DECIMAL(22,2) NOT NULL DEFAULT 0,credit DECIMAL(22,2) NOT NULL DEFAULT 0,outstanding DECIMAL(22,2) NOT NULL DEFAULT 0,status VARCHAR(40) NOT NULL,priority VARCHAR(30) NOT NULL,due_date DATE NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_ap(year,month,vendor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS asset_snapshots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,name VARCHAR(190) NOT NULL,value DECIMAL(22,2) NOT NULL DEFAULT 0,category VARCHAR(30) NOT NULL DEFAULT 'Current',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_asset(year,month,name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS expense_monthly (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,name VARCHAR(190) NOT NULL,value DECIMAL(22,2) NOT NULL DEFAULT 0,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_expense(year,month,name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS targets (
 year INT PRIMARY KEY,revenue DECIMAL(22,2) NOT NULL DEFAULT 0,ebitda DECIMAL(22,2) NOT NULL DEFAULT 0,margin DECIMAL(10,2) NOT NULL DEFAULT 0,type VARCHAR(30) NOT NULL DEFAULT 'Target',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS upload_batches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year INT NOT NULL,month TINYINT NOT NULL,filename VARCHAR(190) NOT NULL,file_hash VARCHAR(128) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'draft',payload_json LONGTEXT NOT NULL,pre_snapshot_json LONGTEXT NULL,
 uploaded_by BIGINT UNSIGNED NULL,published_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,published_at DATETIME NULL,
 INDEX idx_upload_status(status),INDEX idx_upload_year_month(year,month),CONSTRAINT fk_upload_user FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT fk_publish_user FOREIGN KEY(published_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS design_versions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,status VARCHAR(30) NOT NULL DEFAULT 'draft',config_json LONGTEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,published_at DATETIME NULL,
 INDEX idx_design_status(status),CONSTRAINT fk_design_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
$sql[]="CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,entity VARCHAR(80) NULL,entity_id VARCHAR(120) NULL,details_json LONGTEXT NULL,ip_address VARCHAR(64) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_audit_created(created_at),INDEX idx_audit_action(action),CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
foreach($sql as$q)$pdo->exec($q);
$col=$pdo->query("SHOW COLUMNS FROM users LIKE 'session_version'")->fetch();
if(!$col)$pdo->exec("ALTER TABLE users ADD COLUMN session_version INT NOT NULL DEFAULT 1 AFTER is_active");
set_setting('schema_version','4.0.0');
if(get_setting('demo_mode',null)===null)set_setting('demo_mode',true);
echo "SADINO schema migration OK\n";
